const responseObj = {
  hello: "Hey ! How are you doing ? How can I assist you",
  hey: "Hey! What's Up ,How can I aasist you",
  hi: "hello!, How can I assist you",
  "who are you": "I am your friend The Real Time  ChatBot",
  "tell me something about your college": ">>An Autonomous Institute of DBATU, Lonere >>Grade 'A' by NAAC, Bengaluru >>Grade 'A' by University >>Accredited by TATA Consultancy Services",
  name:"R.C.Patel Institute of technology",
  about:" >>An Autonomous Institute of DBATU, Lonere >>Grade 'A' by NAAC, Bengaluru >>Grade 'A' by University >>Accredited by TATA Consultancy Services",
  "which facilities are available": "canteen,Library,Workshop,Computer labs,Auditorium,Elevator,Smart classrooms,Smart boards,Parking,Language labs,Sports room,Stationary,Separate Washrooms,Playground,Water filter,Internet connection,seperate hostels,health clubs,bus",
  workshop:"Yes it is available(Ground Floor Near canteen)",

  canteen:"Yes it is available (at ground floor)",
  library:"Yes it is available(At ground floor)",
  labs:"Yes Labs are available according to different departments",
  auditorium:"Yes Auditorium is available (At second floor)with 100 intake",
  elevator:"Yes ,there are two elevators available in our college",
  classroom:"Yes smart classrooms are available ",
  smartboard:"Yes smart boards are available at every classroom",
  parking:"Yes parking is available (300 intake of vehicles)",
  languagelab:"Yes it is available at second floor",
  sportsroom:"Yes it is available (at second floor)",
  stationary:"Yes it is available (at ground floor)",
  placement: "Yes,100% placement is available ....Highest placement in Khandesh ",
  "is placement available": "Yes,100% placement is available ....Highest placement in Khandesh",
  "is placement available": "Yes,100% placement is available ....Highest placement in Khandesh",
  facilities: "canteen,Library,Workshop,Computer labs,Auditorium,Elevator,Smart classrooms,Smart boards,Parking,Language labs,Sports room,Stationary,Separate Washrooms,Playground,Water filter,Internet connection,seperate hostels,health clubs,bus",
  "what facilities are available": "canteen,Library,Workshop,Computer labs,Auditorium,Elevator,Smart classrooms,Smart boards,Parking,Language labs,Sports room,Stationary,Separate Washrooms,Playground,Water filter,Internet connection,seperate hostels,health clubs,bus",
  "college time": "9 to 5",
  "what facilities are available":"canteen,Library,Workshop,Computer labs,Auditorium,Elevator,Smart classrooms,Smart boards,Parking,Language labs,Sports room,Stationary,Separate Washrooms,Playground,Water filter,Internet connection,seperate hostels,health clubs,bus",
  "admission process": "Admission process for 2022-23 to the first year and direct second year will be conducted through CAP and as per the guidelines of State Government of Maharashtra(M.S.).",
  departments: "Computer Engineering(Intake-180),Electronics & Telecommunication Engineering(Intake-120),Mechanical Engineering(Intake-60),Civil Engineering(Intake-60),Electrical Engineering(Intake-60),Computer Science & Engineering ( Data Science )(Intake-60),Artificial Intelligence And Machine Learning(Intake-60),Applied Sciences and Humanities(Intake-600)",
  scholarship: "Yes,Scholarships are available.....OBC,EBC,SBC,NT,SC,ST",
  fees: "Open-115000,OBC-63800,SBC-12000,SC/ST/NT-12000(All Branches)",
  admission: ">>Application process and deadlines >>Required documents and eligibility criteria >>Entrance exams and their preparation >>Selection criteria and merit-based admissions",
  "student life": ">>Clubs, organizations, and extracurricular activities, >>Campus events and traditions, >>Student support services (counseling, career guidance, health services), >>Opportunities for community engagement and volunteering",
  "computer engineering": ">>HOD-Dr. Nitin Namdeo Patil  >>The department of Computer Engineering has started UG course in 2001, PG course in 2010 and Ph.D. in 2011.  >>Intake 180",
  "data science": ">>HOD-Dr. R.B.Wagh >>Started in 2020  >>Intake 60",
  "electronics and telecommunication engineering": ">>HOD-Prof. Dr. Pramod Jagan Deore  >>Started 2001  >>Intake 120",
  "mechanical engineering": ">>HOD-Prof. Sarode Pravin Laxmanrao  >>Started 2004  >>Intake 60",
  "electrical engineering": ">>HOD-Dr. Vijay Shrinath Patil  >>Started 2012  >>Intake 60",
  "civil engineering": ">>HOD-Prof. Ganesh Vijay Tapkire  >>Started 2010  >>Intake 60",
  "artificial intelligence and machine learning": ">>HOD-Dr. R.B.Wagh  >>Started 2021  >>Intake 60 ",
  "applied sciences and humanities": ">>HOD-Dr. S. V. Desale  >>Started 2001  >>Intake 600",
  president: "Hon. Shri. Amrishbhai R. Patel President, Shirpur Education Society, Shirpur",
  
  director: "Dr. Jayantrao Bhaurao Patil Director",
  activities: ">>NSS >>Sports >>Cultural  >>Saksham",
  contact: "To Contact  RCPIT, >>Contact- (02563) 259600, 801, 802, >> Email-director@rcpit.ac.in, >> Official Website-www.rcpit.ac.in",
  address: "Nimzari Naka Tal-Shirpur(425405),Dist-Dhule,",
  faculty: ">>Well educated  and almost all teachers are Phd holders >>Faculty have their own unique teaching style >>All faculty completed thier post graduation",
  "semester duration": "3/5 months per semester",
  "how many semesters": "8 semesters per B-tech course",
  today: new Date().toDateString(),
  time: new Date().toLocaleTimeString(),
  
};
